

package Controller;
// ALL IMPORTS RELATE TO PARSING OF FILE, SHOULD BE REMOVED IF PARSER IS MADE EXTERNAL
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import org.jdesktop.application.Action;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Jonathan Millar
 * @date 7 Mar 2010
 *
 * Login system for csdlo app
 * !!!!!!!!NOT SECURE!!!!!!!!!! Password is stored as plain text in an xml file
 */
public class Login extends javax.swing.JFrame {

    public static String[] labels = new String[] {"age_label",
                                        "language_label",
                                        "writing_label",
                                        "reading_label",
                                        "speaking_label",
                                        "listening_label",
                                        "prioritygoal_label",
                                        "qualifications_label",
                                        "goal_label",
                                        "activity_label",
                                        "status_label",
                                        "cognitive_label",
                                        "physical_label",
                                        "skill_label",
                                        "role_label",
                                        "keywords_label",
                                        "io_label",
                                        "user_label",
                                        "pass_label",
                                        "passVer_label"
                                        };

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        csdlo = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        submitbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        wronguser = new javax.swing.JLabel();
        wrongpass = new javax.swing.JLabel();
        createUserPanel = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        reading_label = new javax.swing.JLabel();
        speaking_label = new javax.swing.JLabel();
        qualifications_in = new javax.swing.JTextField();
        goal_label = new javax.swing.JLabel();
        age_in = new javax.swing.JTextField();
        speaking_in = new javax.swing.JTextField();
        listening_label = new javax.swing.JLabel();
        prioritygoal_in = new javax.swing.JTextField();
        prioritygoal_label = new javax.swing.JLabel();
        language_in = new javax.swing.JTextField();
        qualifications_label = new javax.swing.JLabel();
        language_label = new javax.swing.JLabel();
        reading_in = new javax.swing.JTextField();
        goal_in = new javax.swing.JTextField();
        age_label = new javax.swing.JLabel();
        writing_in = new javax.swing.JTextField();
        writing_label = new javax.swing.JLabel();
        listening_in = new javax.swing.JTextField();
        age_weight = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        writing_weight = new javax.swing.JSlider();
        language_weight = new javax.swing.JSlider();
        reading_weight = new javax.swing.JSlider();
        speaking_weight = new javax.swing.JSlider();
        listening_weight = new javax.swing.JSlider();
        prioritygoal_weight = new javax.swing.JSlider();
        qualifications_weight = new javax.swing.JSlider();
        goal_weight = new javax.swing.JSlider();
        activity_weight = new javax.swing.JSlider();
        status_weight = new javax.swing.JSlider();
        cognitive_weight = new javax.swing.JSlider();
        physical_weight = new javax.swing.JSlider();
        skill_weight = new javax.swing.JSlider();
        role_weight = new javax.swing.JSlider();
        keywords_weight = new javax.swing.JSlider();
        io_weight = new javax.swing.JSlider();
        activity_in = new javax.swing.JTextField();
        status_in = new javax.swing.JTextField();
        cognitive_in = new javax.swing.JTextField();
        physical_in = new javax.swing.JTextField();
        skill_in = new javax.swing.JTextField();
        role_in = new javax.swing.JTextField();
        keywords_in = new javax.swing.JTextField();
        io_in = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        user_label = new javax.swing.JLabel();
        user_in = new javax.swing.JTextField();
        pass_in = new javax.swing.JTextField();
        passVer_in = new javax.swing.JTextField();
        pass_label = new javax.swing.JLabel();
        passVer_label = new javax.swing.JLabel();
        activity_label = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        cognitive_label = new javax.swing.JLabel();
        physical_label = new javax.swing.JLabel();
        skill_label = new javax.swing.JLabel();
        role_label = new javax.swing.JLabel();
        keywords_label = new javax.swing.JLabel();
        io_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        editUserPanel = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        reading_label1 = new javax.swing.JLabel();
        speaking_label1 = new javax.swing.JLabel();
        qualifications_in1 = new javax.swing.JTextField();
        goal_label1 = new javax.swing.JLabel();
        age_in1 = new javax.swing.JTextField();
        speaking_in1 = new javax.swing.JTextField();
        listening_label1 = new javax.swing.JLabel();
        prioritygoal_in1 = new javax.swing.JTextField();
        prioritygoal_label1 = new javax.swing.JLabel();
        language_in1 = new javax.swing.JTextField();
        qualifications_label1 = new javax.swing.JLabel();
        language_label1 = new javax.swing.JLabel();
        reading_in1 = new javax.swing.JTextField();
        goal_in1 = new javax.swing.JTextField();
        age_label1 = new javax.swing.JLabel();
        writing_in1 = new javax.swing.JTextField();
        writing_label1 = new javax.swing.JLabel();
        listening_in1 = new javax.swing.JTextField();
        age_weight1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        writing_weight1 = new javax.swing.JSlider();
        language_weight1 = new javax.swing.JSlider();
        reading_weight1 = new javax.swing.JSlider();
        speaking_weight1 = new javax.swing.JSlider();
        listening_weight1 = new javax.swing.JSlider();
        prioritygoal_weight1 = new javax.swing.JSlider();
        qualifications_weight1 = new javax.swing.JSlider();
        goal_weight1 = new javax.swing.JSlider();
        activity_weight1 = new javax.swing.JSlider();
        status_weight1 = new javax.swing.JSlider();
        cognitive_weight1 = new javax.swing.JSlider();
        physical_weight1 = new javax.swing.JSlider();
        skill_weight1 = new javax.swing.JSlider();
        role_weight1 = new javax.swing.JSlider();
        keywords_weight1 = new javax.swing.JSlider();
        io_weight1 = new javax.swing.JSlider();
        activity_in1 = new javax.swing.JTextField();
        status_in1 = new javax.swing.JTextField();
        cognitive_in1 = new javax.swing.JTextField();
        physical_in1 = new javax.swing.JTextField();
        skill_in1 = new javax.swing.JTextField();
        role_in1 = new javax.swing.JTextField();
        keywords_in1 = new javax.swing.JTextField();
        io_in1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        user_label1 = new javax.swing.JLabel();
        user_in1 = new javax.swing.JTextField();
        pass_label1 = new javax.swing.JLabel();
        pass_in1 = new javax.swing.JPasswordField();
        activity_label1 = new javax.swing.JLabel();
        status_label1 = new javax.swing.JLabel();
        cognitive_label1 = new javax.swing.JLabel();
        physical_label1 = new javax.swing.JLabel();
        skill_label1 = new javax.swing.JLabel();
        role_label1 = new javax.swing.JLabel();
        keywords_label1 = new javax.swing.JLabel();
        io_label1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        status1 = new javax.swing.JLabel();
        LoadUser = new javax.swing.JButton();
        passVer_label1 = new javax.swing.JLabel();
        passVer_in1 = new javax.swing.JTextField();
        passNew_label1 = new javax.swing.JLabel();
        passNew_in1 = new javax.swing.JTextField();

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        csdlo.setName("csdlo"); // NOI18N

        loginPanel.setName("loginPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Controller.EE4913App.class).getContext().getResourceMap(Login.class);
        Title.setFont(resourceMap.getFont("Title.font")); // NOI18N
        Title.setText(resourceMap.getString("Title.text")); // NOI18N
        Title.setName("Title"); // NOI18N

        username.setFont(resourceMap.getFont("username.font")); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText(resourceMap.getString("username.text")); // NOI18N
        username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        username.setName("username"); // NOI18N

        password.setFont(resourceMap.getFont("password.font")); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText(resourceMap.getString("password.text")); // NOI18N
        password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        password.setName("password"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Controller.EE4913App.class).getContext().getActionMap(Login.class, this);
        submitbutton.setAction(actionMap.get("EE4913App")); // NOI18N
        submitbutton.setText(resourceMap.getString("submitbutton.text")); // NOI18N
        submitbutton.setName("submitbutton"); // NOI18N
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        exitbutton.setAction(actionMap.get("quit")); // NOI18N
        exitbutton.setText(resourceMap.getString("exitbutton.text")); // NOI18N
        exitbutton.setName("exitbutton"); // NOI18N
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        wronguser.setForeground(resourceMap.getColor("wronguser.foreground")); // NOI18N
        wronguser.setText(resourceMap.getString("wronguser.text")); // NOI18N
        wronguser.setName("wronguser"); // NOI18N

        wrongpass.setForeground(resourceMap.getColor("wrongpass.foreground")); // NOI18N
        wrongpass.setText(resourceMap.getString("wrongpass.text")); // NOI18N
        wrongpass.setName("wrongpass"); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(submitbutton)
                .addGap(52, 52, 52)
                .addComponent(exitbutton)
                .addGap(331, 331, 331))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(330, 330, 330))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wronguser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrongpass, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitbutton)
                            .addComponent(exitbutton)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(wronguser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(wrongpass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        csdlo.addTab(resourceMap.getString("loginPanel.TabConstraints.tabTitle"), loginPanel); // NOI18N

        createUserPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        createUserPanel.setName("createUserPanel"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(761, 948));

        reading_label.setText(resourceMap.getString("reading_label.text")); // NOI18N
        reading_label.setName("reading_label"); // NOI18N

        speaking_label.setText(resourceMap.getString("speaking_label.text")); // NOI18N
        speaking_label.setName("speaking_label"); // NOI18N

        qualifications_in.setText(resourceMap.getString("qualifications_in.text")); // NOI18N
        qualifications_in.setName("qualifications_in"); // NOI18N

        goal_label.setText(resourceMap.getString("goal_label.text")); // NOI18N
        goal_label.setName("goal_label"); // NOI18N

        age_in.setText(resourceMap.getString("age_in.text")); // NOI18N
        age_in.setName("age_in"); // NOI18N

        speaking_in.setText(resourceMap.getString("speaking_in.text")); // NOI18N
        speaking_in.setName("speaking_in"); // NOI18N

        listening_label.setText(resourceMap.getString("listening_label.text")); // NOI18N
        listening_label.setName("listening_label"); // NOI18N

        prioritygoal_in.setText(resourceMap.getString("prioritygoal_in.text")); // NOI18N
        prioritygoal_in.setName("prioritygoal_in"); // NOI18N

        prioritygoal_label.setText(resourceMap.getString("prioritygoal_label.text")); // NOI18N
        prioritygoal_label.setName("prioritygoal_label"); // NOI18N

        language_in.setText(resourceMap.getString("language_in.text")); // NOI18N
        language_in.setName("language_in"); // NOI18N

        qualifications_label.setText(resourceMap.getString("qualifications_label.text")); // NOI18N
        qualifications_label.setName("qualifications_label"); // NOI18N

        language_label.setText(resourceMap.getString("language_label.text")); // NOI18N
        language_label.setName("language_label"); // NOI18N

        reading_in.setText(resourceMap.getString("reading_in.text")); // NOI18N
        reading_in.setName("reading_in"); // NOI18N

        goal_in.setName("goal_in"); // NOI18N

        age_label.setText(resourceMap.getString("age_label.text")); // NOI18N
        age_label.setName("age_label"); // NOI18N

        writing_in.setText(resourceMap.getString("writing_in.text")); // NOI18N
        writing_in.setName("writing_in"); // NOI18N

        writing_label.setText(resourceMap.getString("writing_label.text")); // NOI18N
        writing_label.setName("writing_label"); // NOI18N

        listening_in.setText(resourceMap.getString("listening_in.text")); // NOI18N
        listening_in.setName("listening_in"); // NOI18N

        age_weight.setValue(90);
        age_weight.setName("age_weight"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        writing_weight.setValue(90);
        writing_weight.setName("writing_weight"); // NOI18N

        language_weight.setValue(10);
        language_weight.setName("language_weight"); // NOI18N

        reading_weight.setValue(10);
        reading_weight.setName("reading_weight"); // NOI18N

        speaking_weight.setValue(90);
        speaking_weight.setName("speaking_weight"); // NOI18N

        listening_weight.setValue(10);
        listening_weight.setName("listening_weight"); // NOI18N

        prioritygoal_weight.setValue(90);
        prioritygoal_weight.setName("prioritygoal_weight"); // NOI18N

        qualifications_weight.setValue(10);
        qualifications_weight.setName("qualifications_weight"); // NOI18N

        goal_weight.setValue(90);
        goal_weight.setName("goal_weight"); // NOI18N

        activity_weight.setValue(10);
        activity_weight.setName("activity_weight"); // NOI18N

        status_weight.setValue(90);
        status_weight.setName("status_weight"); // NOI18N

        cognitive_weight.setValue(10);
        cognitive_weight.setName("cognitive_weight"); // NOI18N

        physical_weight.setValue(10);
        physical_weight.setName("physical_weight"); // NOI18N

        skill_weight.setValue(10);
        skill_weight.setName("skill_weight"); // NOI18N

        role_weight.setValue(90);
        role_weight.setName("role_weight"); // NOI18N

        keywords_weight.setValue(10);
        keywords_weight.setName("keywords_weight"); // NOI18N

        io_weight.setName("io_weight"); // NOI18N

        activity_in.setText(resourceMap.getString("activity_in.text")); // NOI18N
        activity_in.setName("activity_in"); // NOI18N

        status_in.setText(resourceMap.getString("status_in.text")); // NOI18N
        status_in.setName("status_in"); // NOI18N

        cognitive_in.setText(resourceMap.getString("cognitive_in.text")); // NOI18N
        cognitive_in.setName("cognitive_in"); // NOI18N

        physical_in.setText(resourceMap.getString("physical_in.text")); // NOI18N
        physical_in.setName("physical_in"); // NOI18N

        skill_in.setText(resourceMap.getString("skill_in.text")); // NOI18N
        skill_in.setName("skill_in"); // NOI18N

        role_in.setText(resourceMap.getString("role_in.text")); // NOI18N
        role_in.setName("role_in"); // NOI18N

        keywords_in.setText(resourceMap.getString("keywords_in.text")); // NOI18N
        keywords_in.setName("keywords_in"); // NOI18N

        io_in.setText(resourceMap.getString("io_in.text")); // NOI18N
        io_in.setName("io_in"); // NOI18N

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        user_label.setText(resourceMap.getString("user_label.text")); // NOI18N
        user_label.setName("user_label"); // NOI18N

        user_in.setName("user_in"); // NOI18N

        pass_in.setName("pass_in"); // NOI18N

        passVer_in.setName("passVer_in"); // NOI18N

        pass_label.setText(resourceMap.getString("pass_label.text")); // NOI18N
        pass_label.setName("pass_label"); // NOI18N

        passVer_label.setText(resourceMap.getString("passVer_label.text")); // NOI18N
        passVer_label.setName("passVer_label"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user_label)
                    .addComponent(pass_label)
                    .addComponent(passVer_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passVer_in, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(pass_in, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(user_in, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_label)
                    .addComponent(user_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passVer_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passVer_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        activity_label.setText(resourceMap.getString("activity_label.text")); // NOI18N
        activity_label.setName("activity_label"); // NOI18N

        status_label.setText(resourceMap.getString("status_label.text")); // NOI18N
        status_label.setName("status_label"); // NOI18N

        cognitive_label.setText(resourceMap.getString("cognitive_label.text")); // NOI18N
        cognitive_label.setName("cognitive_label"); // NOI18N

        physical_label.setText(resourceMap.getString("physical_label.text")); // NOI18N
        physical_label.setName("physical_label"); // NOI18N

        skill_label.setText(resourceMap.getString("skill_label.text")); // NOI18N
        skill_label.setName("skill_label"); // NOI18N

        role_label.setText(resourceMap.getString("role_label.text")); // NOI18N
        role_label.setName("role_label"); // NOI18N

        keywords_label.setText(resourceMap.getString("keywords_label.text")); // NOI18N
        keywords_label.setName("keywords_label"); // NOI18N

        io_label.setText(resourceMap.getString("io_label.text")); // NOI18N
        io_label.setName("io_label"); // NOI18N

        jButton1.setAction(actionMap.get("createNewUser")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        status.setFont(resourceMap.getFont("status.font")); // NOI18N
        status.setForeground(resourceMap.getColor("status.foreground")); // NOI18N
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText(resourceMap.getString("status.text")); // NOI18N
        status.setName("status"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(writing_label)
                    .addComponent(reading_label)
                    .addComponent(speaking_label)
                    .addComponent(listening_label)
                    .addComponent(prioritygoal_label)
                    .addComponent(qualifications_label)
                    .addComponent(age_label)
                    .addComponent(language_label)
                    .addComponent(goal_label)
                    .addComponent(activity_label)
                    .addComponent(status_label)
                    .addComponent(cognitive_label)
                    .addComponent(physical_label)
                    .addComponent(skill_label)
                    .addComponent(role_label)
                    .addComponent(keywords_label)
                    .addComponent(io_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(language_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(age_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(writing_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(reading_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(speaking_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(listening_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(prioritygoal_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(qualifications_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(goal_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(activity_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(status_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(cognitive_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(physical_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(skill_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(role_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(keywords_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(io_in, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(io_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(keywords_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(role_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(skill_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(physical_weight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(cognitive_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(status_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(activity_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(goal_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(qualifications_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(prioritygoal_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(listening_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(speaking_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(reading_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(writing_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(language_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(age_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(age_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(age_label))
                            .addComponent(age_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(language_in, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(language_label))
                            .addComponent(language_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(writing_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(writing_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(writing_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reading_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(reading_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reading_label))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(status)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(speaking_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(speaking_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(speaking_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listening_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listening_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listening_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prioritygoal_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prioritygoal_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prioritygoal_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qualifications_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qualifications_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qualifications_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goal_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(goal_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(goal_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(activity_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(activity_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(activity_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(status_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(status_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(status_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cognitive_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cognitive_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cognitive_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(physical_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(physical_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(physical_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skill_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(skill_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(skill_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(role_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(role_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(role_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keywords_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(keywords_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(keywords_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(io_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(io_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(io_label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createUserPanel.setViewportView(jPanel2);

        csdlo.addTab(resourceMap.getString("createUserPanel.TabConstraints.tabTitle"), createUserPanel); // NOI18N

        editUserPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        editUserPanel.setName("editUserPanel"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(761, 911));

        reading_label1.setText(resourceMap.getString("reading_label1.text")); // NOI18N
        reading_label1.setName("reading_label1"); // NOI18N

        speaking_label1.setText(resourceMap.getString("speaking_label1.text")); // NOI18N
        speaking_label1.setName("speaking_label1"); // NOI18N

        qualifications_in1.setText(resourceMap.getString("qualifications_in1.text")); // NOI18N
        qualifications_in1.setName("qualifications_in1"); // NOI18N

        goal_label1.setText(resourceMap.getString("goal_label1.text")); // NOI18N
        goal_label1.setName("goal_label1"); // NOI18N

        age_in1.setText(resourceMap.getString("age_in1.text")); // NOI18N
        age_in1.setName("age_in1"); // NOI18N

        speaking_in1.setText(resourceMap.getString("speaking_in1.text")); // NOI18N
        speaking_in1.setName("speaking_in1"); // NOI18N

        listening_label1.setText(resourceMap.getString("listening_label1.text")); // NOI18N
        listening_label1.setName("listening_label1"); // NOI18N

        prioritygoal_in1.setText(resourceMap.getString("prioritygoal_in1.text")); // NOI18N
        prioritygoal_in1.setName("prioritygoal_in1"); // NOI18N

        prioritygoal_label1.setText(resourceMap.getString("prioritygoal_label1.text")); // NOI18N
        prioritygoal_label1.setName("prioritygoal_label1"); // NOI18N

        language_in1.setText(resourceMap.getString("language_in1.text")); // NOI18N
        language_in1.setName("language_in1"); // NOI18N

        qualifications_label1.setText(resourceMap.getString("qualifications_label1.text")); // NOI18N
        qualifications_label1.setName("qualifications_label1"); // NOI18N

        language_label1.setText(resourceMap.getString("language_label1.text")); // NOI18N
        language_label1.setName("language_label1"); // NOI18N

        reading_in1.setText(resourceMap.getString("reading_in1.text")); // NOI18N
        reading_in1.setName("reading_in1"); // NOI18N

        goal_in1.setName("goal_in1"); // NOI18N

        age_label1.setText(resourceMap.getString("age_label1.text")); // NOI18N
        age_label1.setName("age_label1"); // NOI18N

        writing_in1.setText(resourceMap.getString("writing_in1.text")); // NOI18N
        writing_in1.setName("writing_in1"); // NOI18N

        writing_label1.setText(resourceMap.getString("writing_label1.text")); // NOI18N
        writing_label1.setName("writing_label1"); // NOI18N

        listening_in1.setText(resourceMap.getString("listening_in1.text")); // NOI18N
        listening_in1.setName("listening_in1"); // NOI18N

        age_weight1.setName("age_weight1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        writing_weight1.setName("writing_weight1"); // NOI18N

        language_weight1.setName("language_weight1"); // NOI18N

        reading_weight1.setName("reading_weight1"); // NOI18N

        speaking_weight1.setName("speaking_weight1"); // NOI18N

        listening_weight1.setName("listening_weight1"); // NOI18N

        prioritygoal_weight1.setName("prioritygoal_weight1"); // NOI18N

        qualifications_weight1.setName("qualifications_weight1"); // NOI18N

        goal_weight1.setName("goal_weight1"); // NOI18N

        activity_weight1.setName("activity_weight1"); // NOI18N

        status_weight1.setName("status_weight1"); // NOI18N

        cognitive_weight1.setName("cognitive_weight1"); // NOI18N

        physical_weight1.setName("physical_weight1"); // NOI18N

        skill_weight1.setName("skill_weight1"); // NOI18N

        role_weight1.setName("role_weight1"); // NOI18N

        keywords_weight1.setName("keywords_weight1"); // NOI18N

        io_weight1.setName("io_weight1"); // NOI18N

        activity_in1.setText(resourceMap.getString("activity_in1.text")); // NOI18N
        activity_in1.setName("activity_in1"); // NOI18N

        status_in1.setText(resourceMap.getString("status_in1.text")); // NOI18N
        status_in1.setName("status_in1"); // NOI18N

        cognitive_in1.setText(resourceMap.getString("cognitive_in1.text")); // NOI18N
        cognitive_in1.setName("cognitive_in1"); // NOI18N

        physical_in1.setName("physical_in1"); // NOI18N

        skill_in1.setText(resourceMap.getString("skill_in1.text")); // NOI18N
        skill_in1.setName("skill_in1"); // NOI18N

        role_in1.setText(resourceMap.getString("role_in1.text")); // NOI18N
        role_in1.setName("role_in1"); // NOI18N

        keywords_in1.setText(resourceMap.getString("keywords_in1.text")); // NOI18N
        keywords_in1.setName("keywords_in1"); // NOI18N

        io_in1.setText(resourceMap.getString("io_in1.text")); // NOI18N
        io_in1.setName("io_in1"); // NOI18N

        jPanel5.setBackground(resourceMap.getColor("jPanel5.background")); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        user_label1.setText(resourceMap.getString("user_label1.text")); // NOI18N
        user_label1.setName("user_label1"); // NOI18N

        user_in1.setName("user_in1"); // NOI18N

        pass_label1.setText(resourceMap.getString("pass_label1.text")); // NOI18N
        pass_label1.setName("pass_label1"); // NOI18N

        pass_in1.setText(resourceMap.getString("pass_in1.text")); // NOI18N
        pass_in1.setName("pass_in1"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user_label1)
                    .addComponent(pass_label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(user_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_label1)
                    .addComponent(user_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_label1)
                    .addComponent(pass_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        activity_label1.setText(resourceMap.getString("activity_label1.text")); // NOI18N
        activity_label1.setName("activity_label1"); // NOI18N

        status_label1.setText(resourceMap.getString("status_label1.text")); // NOI18N
        status_label1.setName("status_label1"); // NOI18N

        cognitive_label1.setText(resourceMap.getString("cognitive_label1.text")); // NOI18N
        cognitive_label1.setName("cognitive_label1"); // NOI18N

        physical_label1.setText(resourceMap.getString("physical_label1.text")); // NOI18N
        physical_label1.setName("physical_label1"); // NOI18N

        skill_label1.setText(resourceMap.getString("skill_label1.text")); // NOI18N
        skill_label1.setName("skill_label1"); // NOI18N

        role_label1.setText(resourceMap.getString("role_label1.text")); // NOI18N
        role_label1.setName("role_label1"); // NOI18N

        keywords_label1.setText(resourceMap.getString("keywords_label1.text")); // NOI18N
        keywords_label1.setName("keywords_label1"); // NOI18N

        io_label1.setText(resourceMap.getString("io_label1.text")); // NOI18N
        io_label1.setName("io_label1"); // NOI18N

        jButton2.setAction(actionMap.get("saveUser")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        status1.setFont(resourceMap.getFont("status1.font")); // NOI18N
        status1.setForeground(resourceMap.getColor("status1.foreground")); // NOI18N
        status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status1.setText(resourceMap.getString("status1.text")); // NOI18N
        status1.setName("status1"); // NOI18N

        LoadUser.setAction(actionMap.get("loadUserProfile")); // NOI18N
        LoadUser.setText(resourceMap.getString("LoadUser.text")); // NOI18N
        LoadUser.setName("LoadUser"); // NOI18N

        passVer_label1.setText(resourceMap.getString("passVer_label1.text")); // NOI18N
        passVer_label1.setName("passVer_label1"); // NOI18N

        passVer_in1.setName("passVer_in1"); // NOI18N

        passNew_label1.setText(resourceMap.getString("passNew_label1.text")); // NOI18N
        passNew_label1.setName("passNew_label1"); // NOI18N

        passNew_in1.setText(resourceMap.getString("passNew_in1.text")); // NOI18N
        passNew_in1.setName("passNew_in1"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passNew_label1)
                    .addComponent(writing_label1)
                    .addComponent(reading_label1)
                    .addComponent(speaking_label1)
                    .addComponent(listening_label1)
                    .addComponent(prioritygoal_label1)
                    .addComponent(qualifications_label1)
                    .addComponent(age_label1)
                    .addComponent(language_label1)
                    .addComponent(goal_label1)
                    .addComponent(activity_label1)
                    .addComponent(status_label1)
                    .addComponent(cognitive_label1)
                    .addComponent(physical_label1)
                    .addComponent(skill_label1)
                    .addComponent(role_label1)
                    .addComponent(keywords_label1)
                    .addComponent(io_label1)
                    .addComponent(passVer_label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passVer_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(passNew_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(language_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(age_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(writing_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(reading_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(speaking_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(listening_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(prioritygoal_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(qualifications_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(goal_in1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(activity_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(status_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(cognitive_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(physical_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(skill_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(role_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(keywords_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(io_in1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(io_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(keywords_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(role_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(skill_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(physical_weight1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(cognitive_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(status_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(activity_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(goal_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(qualifications_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(prioritygoal_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(listening_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(speaking_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(reading_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(writing_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(language_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(age_weight1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(LoadUser, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(status1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(age_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(age_label1))
                            .addComponent(age_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(language_in1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(language_label1))
                            .addComponent(language_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(writing_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(writing_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(writing_label1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reading_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(reading_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reading_label1))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(LoadUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(speaking_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(speaking_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(speaking_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listening_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listening_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listening_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prioritygoal_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prioritygoal_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prioritygoal_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qualifications_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qualifications_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qualifications_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goal_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(goal_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(goal_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(activity_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(activity_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(activity_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(status_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(status_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(status_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cognitive_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cognitive_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cognitive_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(physical_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(physical_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(physical_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skill_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(skill_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(skill_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(role_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(role_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(role_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keywords_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(keywords_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(keywords_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(io_weight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(io_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(io_label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passNew_label1)
                    .addComponent(passNew_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passVer_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passVer_label1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editUserPanel.setViewportView(jPanel4);

        csdlo.addTab(resourceMap.getString("editUserPanel.TabConstraints.tabTitle"), editUserPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(csdlo, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(csdlo, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed

}//GEN-LAST:event_exitbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // At button click error messages should be cleared
        wronguser.setText("");
        wrongpass.setText("");

        // Grab user and password and convert to a string
        String pass = new String(password.getPassword());
        String user = username.getText();  // Grab user name from text field


        //==================================================//
        //--------------------------------------------------//
        //~~MUST SET FULL PATH TO XML FILE TO WORK IN AJAX~~//
        //--------------------------------------------------//
        //==================================================//
        String fileName = "src/users/"+user+".xml";  // Process into a file name




        // Search for user name
        // If found seach through attributes in file for password field
        // If match then launch app
        DocumentBuilderFactory docBuilderfact = DocumentBuilderFactory.newInstance();
        try {
            DocumentBuilder docBuilder = docBuilderfact.newDocumentBuilder();
            Document userprofile = docBuilder.parse(new FileInputStream(fileName));

            NodeList attNodes = userprofile.getElementsByTagName("Attribute");

            // Loop through all atribute fields until password field found
            // Allows for password to be any attribute number in xml file
            for (int i = 0 ; i < attNodes.getLength() ; ++i) {              // Loops through attributes
                NodeList childNodes = attNodes.item(i).getChildNodes();
                String name = null,value = null ;
                for ( int j = 0 ; j < childNodes.getLength() ; ++j ) {      // Loops through attribute elements
                    if ( childNodes.item(j) instanceof org.w3c.dom.Element ) {
                        Element el = (Element)childNodes.item(j);
                        if ( el.getNodeName().equals("Name")) name = el.getTextContent();
                        else if ( el.getNodeName().equals("Value")) value = el.getTextContent();
                    }
                }



                //---------------------PASSWORD VERIFICATION-----------------------------------\\

                // Verify password
                // If correct launch app, else tell user
                if ( (name.equalsIgnoreCase("password")) && (pass.equalsIgnoreCase(value))) {
                    EE4913App.launch2();
                    this.setVisible(false); // Comment out if debugging
                    break;
                } else if ( (name.equalsIgnoreCase("password")) && !(pass.equalsIgnoreCase(value))) {
                    // User exists but wrong pass
                    wrongpass.setText("**WRONG PASSWORD**");
                }
                //------------------------------------------------------------------------------\\


            }
        } catch (FileNotFoundException e) {
            // could not find user
            wronguser.setText("** WRONG USER **");
        } catch (ParserConfigurationException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (SAXException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


    }//GEN-LAST:event_submitbuttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadUser;
    private javax.swing.JLabel Title;
    public static javax.swing.JTextField activity_in;
    public static javax.swing.JTextField activity_in1;
    public static javax.swing.JLabel activity_label;
    public static javax.swing.JLabel activity_label1;
    public static javax.swing.JSlider activity_weight;
    public static javax.swing.JSlider activity_weight1;
    public static javax.swing.JTextField age_in;
    public static javax.swing.JTextField age_in1;
    public static javax.swing.JLabel age_label;
    public static javax.swing.JLabel age_label1;
    public static javax.swing.JSlider age_weight;
    public static javax.swing.JSlider age_weight1;
    public static javax.swing.JTextField cognitive_in;
    public static javax.swing.JTextField cognitive_in1;
    public static javax.swing.JLabel cognitive_label;
    public static javax.swing.JLabel cognitive_label1;
    public static javax.swing.JSlider cognitive_weight;
    public static javax.swing.JSlider cognitive_weight1;
    private javax.swing.JScrollPane createUserPanel;
    private javax.swing.JTabbedPane csdlo;
    private javax.swing.JScrollPane editUserPanel;
    private javax.swing.JButton exitbutton;
    public static javax.swing.JTextField goal_in;
    public static javax.swing.JTextField goal_in1;
    public static javax.swing.JLabel goal_label;
    public static javax.swing.JLabel goal_label1;
    public static javax.swing.JSlider goal_weight;
    public static javax.swing.JSlider goal_weight1;
    public static javax.swing.JTextField io_in;
    public static javax.swing.JTextField io_in1;
    public static javax.swing.JLabel io_label;
    public static javax.swing.JLabel io_label1;
    public static javax.swing.JSlider io_weight;
    public static javax.swing.JSlider io_weight1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField keywords_in;
    public static javax.swing.JTextField keywords_in1;
    public static javax.swing.JLabel keywords_label;
    public static javax.swing.JLabel keywords_label1;
    public static javax.swing.JSlider keywords_weight;
    public static javax.swing.JSlider keywords_weight1;
    public static javax.swing.JTextField language_in;
    public static javax.swing.JTextField language_in1;
    public static javax.swing.JLabel language_label;
    public static javax.swing.JLabel language_label1;
    public static javax.swing.JSlider language_weight;
    public static javax.swing.JSlider language_weight1;
    public static javax.swing.JTextField listening_in;
    public static javax.swing.JTextField listening_in1;
    public static javax.swing.JLabel listening_label;
    public static javax.swing.JLabel listening_label1;
    public static javax.swing.JSlider listening_weight;
    public static javax.swing.JSlider listening_weight1;
    private javax.swing.JPanel loginPanel;
    public static javax.swing.JTextField passNew_in1;
    public static javax.swing.JLabel passNew_label1;
    public static javax.swing.JTextField passVer_in;
    public static javax.swing.JTextField passVer_in1;
    public static javax.swing.JLabel passVer_label;
    public static javax.swing.JLabel passVer_label1;
    public static javax.swing.JTextField pass_in;
    protected static javax.swing.JPasswordField pass_in1;
    public static javax.swing.JLabel pass_label;
    public static javax.swing.JLabel pass_label1;
    public static javax.swing.JPasswordField password;
    public static javax.swing.JTextField physical_in;
    public static javax.swing.JTextField physical_in1;
    public static javax.swing.JLabel physical_label;
    public static javax.swing.JLabel physical_label1;
    public static javax.swing.JSlider physical_weight;
    public static javax.swing.JSlider physical_weight1;
    public static javax.swing.JTextField prioritygoal_in;
    public static javax.swing.JTextField prioritygoal_in1;
    public static javax.swing.JLabel prioritygoal_label;
    public static javax.swing.JLabel prioritygoal_label1;
    public static javax.swing.JSlider prioritygoal_weight;
    public static javax.swing.JSlider prioritygoal_weight1;
    public static javax.swing.JTextField qualifications_in;
    public static javax.swing.JTextField qualifications_in1;
    public static javax.swing.JLabel qualifications_label;
    public static javax.swing.JLabel qualifications_label1;
    public static javax.swing.JSlider qualifications_weight;
    public static javax.swing.JSlider qualifications_weight1;
    public static javax.swing.JTextField reading_in;
    public static javax.swing.JTextField reading_in1;
    public static javax.swing.JLabel reading_label;
    public static javax.swing.JLabel reading_label1;
    public static javax.swing.JSlider reading_weight;
    public static javax.swing.JSlider reading_weight1;
    public static javax.swing.JTextField role_in;
    public static javax.swing.JTextField role_in1;
    public static javax.swing.JLabel role_label;
    public static javax.swing.JLabel role_label1;
    public static javax.swing.JSlider role_weight;
    public static javax.swing.JSlider role_weight1;
    public static javax.swing.JTextField skill_in;
    public static javax.swing.JTextField skill_in1;
    public static javax.swing.JLabel skill_label;
    public static javax.swing.JLabel skill_label1;
    public static javax.swing.JSlider skill_weight;
    public static javax.swing.JSlider skill_weight1;
    public static javax.swing.JTextField speaking_in;
    public static javax.swing.JTextField speaking_in1;
    public static javax.swing.JLabel speaking_label;
    public static javax.swing.JLabel speaking_label1;
    public static javax.swing.JSlider speaking_weight;
    public static javax.swing.JSlider speaking_weight1;
    public static javax.swing.JLabel status;
    public static javax.swing.JLabel status1;
    public static javax.swing.JTextField status_in;
    public static javax.swing.JTextField status_in1;
    public static javax.swing.JLabel status_label;
    public static javax.swing.JLabel status_label1;
    public static javax.swing.JSlider status_weight;
    public static javax.swing.JSlider status_weight1;
    private javax.swing.JButton submitbutton;
    public static javax.swing.JTextField user_in;
    public static javax.swing.JTextField user_in1;
    public static javax.swing.JLabel user_label;
    public static javax.swing.JLabel user_label1;
    public static javax.swing.JTextField username;
    protected static javax.swing.JTextField writing_in;
    public static javax.swing.JTextField writing_in1;
    public static javax.swing.JLabel writing_label;
    public static javax.swing.JLabel writing_label1;
    public static javax.swing.JSlider writing_weight;
    public static javax.swing.JSlider writing_weight1;
    public static javax.swing.JLabel wrongpass;
    public static javax.swing.JLabel wronguser;
    // End of variables declaration//GEN-END:variables

 
}
